### ISSUE TITLE
Implement authentication macro

### ISSUE THREAD

**Issue by pixix4** [ascii-dresden/ascii-pay-server#11]
Enforce authentication or redirect to login

**Comment by Feliix42** [comment]
Okay, so the fun thing is that the middleware, when retrieving the `LoggedUser` for literally any path except for the login, is already throwing an `Unauthorized` HTTP status code because its return type is `LoggedAccount` which leaves no room for a more graceful handling using a `Option`al.

I would advocate for altering the retrieved data type from the middleware to an optional which is then unwrapped in the macro when checking the privilege level. Do you have any other ideas?

**Comment by pixix4** [comment]
The `Option` solution sounds good. Alternativly `LoggedAccount` can be changed to an enum and have an internal state. But an `Option` should be enough
